general:
steps:
  mtaBuild:
    buildTarget: 'CF'
 cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'ee01d6fftrial'
      space: 'work'
      credentialsId: 'CF'
